[versions]
java = "21"
springBoot = "3.5.8"
dependencyManagement = "1.1.7"

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "dependencyManagement" }
